<?php return [
    'enabledPlugins' => [],
    'licenceKey' => '',
    'updatesUrl' => 'http://updates.artweb.ee/api/',
    'errorReporting' => E_ALL | E_STRICT,
    'publicSessionLifeTime' => 3600,
    'adminSessionLifeTime' => 86400,
    'defaultSessionLifeTime' => 1440,
    'displaySubCategoryProducts' => true,
    'vatRate' => 1.2,
    'displayVat' => true,
    'cacheEnabled' => false,
    'publicTheme' => 'project',
    'mobileTheme' => 'projectMobile',
    'mobileRedirectionEnabled' => false,
    'mobileDefaultDeviceMode' => 'tablet',
    'mobileRedirection' => [
        'phone' => true,
        'tablet' => true,
    ],
    'rssTheme' => 'projectRss',
    'googleAnalyticsDomain' => '',
    'googleAnalyticsId' => '',
    'dpdEnabled' => false,
    'timeZone' => 'Europe/Tallinn',
    'newProductLimit' => 7776000,
    'protocol' => 'http://',
    'rootMarkerPublic' => 'public_root',
    'rootMarkerAdmin' => 'admin_root',
    'pricesContainVat' => true,
    'templateTypeCategorySubCategory' => 'thumbnailsmall',
    'templateTypeCategoryProduct' => 'thumbnail',
    'accLicenseTestKey' => '498ec72c-e8e7-48f2-b300-d95666aeb141',
    'shoppingasketAccountStepEnabled' => false,
    'shoppingasketAccountStepSkippable' => true,
    'redirectImagesWithDeprecatedParameters' => false,
];